FROM golang:1.22.3-alpine3.18 AS builder

# Move to working directory (/build).
WORKDIR /build

# Copy and download dependency using go mod.
COPY go.mod go.sum ./
RUN go mod download

# Copy the code into the container.
COPY ./order-management-service/*.go ./
COPY ./common/*.go ./common/

# Set necessary environment variables needed 
# for our image and build the sender.
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN go build -ldflags="-s -w" -o oms .

# Generate Swagger files
RUN go get -u github.com/swaggo/swag/cmd/swag
RUN go install github.com/swaggo/swag/cmd/swag
RUN swag init -g ./main.go

FROM scratch

# Copy binary and config files from /build 
# to root folder of scratch container.
COPY --from=builder ["/build/oms", "/"]

# Copy Swagger JSON file from /build/docs to /docs in the scratch container.
COPY --from=builder ["/build/docs/swagger.json", "/docs/swagger.json"]

# Command to run when starting the container.
ENTRYPOINT ["/oms"]